

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /media/whome/config/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ayush
      - MYSQL_PASSWORD=ayush
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 9973:80
    links:
      - db
    volumes:
      - /media/whome/config/nextcloud/app:/var/www/html
    environment:
      - MYSQL_PASSWORD=ayush
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
