version: '3.8'

services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    restart: unless-stopped
    ports:
      - "8444:80"
    environment:
      - TZ=Asia/Kolkata
      - CRON_MIN=1,31
    volumes:
      - /media/whome/config/freshrss/freshrss_data:/var/www/FreshRSS/data
      - /media/whome/config/freshrss/freshrss_extensions:/var/www/FreshRSS/extensions
    logging:
      options:
        max-size: "10m"
